### ISSUE TITLE
Entry with entry_type='new_entry' and update_type='End of Policy'

### ISSUE THREAD

**Issue by AlexxxH** [saudiwin/corona_tscs#43]
In the dataset "CoronaNet Database Version 1.0 (core)", the row with record ID "R_1lhMRHEYaVpBP32NA" has entry_type='new_entry' and update_type='End of Policy'. The description for this entry is: 

"On May 4, Andalusia enters Phase 0 of Spain’s 4-phase de escalation plan. Furthermore, the previously instilled curfew allowing people 14 or older (but less than 70/ not dependent) to exercise outside (on a bike within one's city or a one-hour walk within 0.5 miles of one's home) between 8 p.m. to 11 p.m. (or 6 a.m. to 10 a.m.)  is now included in this Phase 0. Due to the asynchronous nature of the de escalation plan, this curfew is now viewed as a sub-national policy, as how long it lasts locally largely depends on how well Andalusia handles its virus environment."

**Comment by IsaacBravo** [comment]
Hi, thank you very much for pointing it out, however, it is not possible to know which record corresponds since that record_id has four updates, so it would be ideal to have the record_id of the update or at least the end_date of the record you want to modify. In any case, we will take this into account when performing the Data Integration Process for the Andalusia region.
